### ISSUE TITLE
fix README rendering tags

### ISSUE THREAD

**Issue by theRemix** [devleague/behavior-driven-shopping-list#3]
`...wrapping it in a "
" tags`

should be

```
...wrapping it in a "</ul>" tags
```

wrapping it in code backticks should do the trick

**Comment by JoeKarlsson** [comment]
Fixed this issue and added notes about ES6 String Templates
![screen shot 2016-06-27 at 1 56 21 pm](https://cloud.githubusercontent.com/assets/4650739/16399529/fb7608c0-3c6e-11e6-96f5-dad9040efe71.png)
